kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: grafana-postgres
  labels:
    system: openstack
    service: monitoring
    component: grafana
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: grafana-postgres
        component: grafana-postgres
      annotations:
        checksum/create-session-table.sql: {{ include "grafana/templates/_create-session-table.sql.tpl" . | sha256sum }}
        checksum/postgres-start: {{ include "grafana/templates/_postgres-start.tpl" . | sha256sum }}
        checksum/helpers: {{ include "grafana/templates/_helpers.tpl" . | sha256sum }}
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: storage
{{- if not .Values.persistence.enabled }}
          emptyDir: {}
{{- else }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name | quote }}
{{- end }}
        - name: grafana-bin
          configMap:
            name: grafana-bin
        - name: grafana-etc
          configMap:
            name: grafana-etc
      containers:
        - name: postgres
          image: {{.Values.postgres.image}}:{{.Values.postgres.image_version}}
          env:
            - name: PGDATA
              value: /postgresql/data
            - name: POSTGRES_DB
              value: grafana
            - name: POSTGRES_PASSWORD
              value: {{.Values.postgres.password}}
          command:
            - /bin/bash
          args:
            - /grafana-bin/postgres-start
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /postgresql
            - name: grafana-bin
              mountPath: /grafana-bin
            - name: grafana-etc
              mountPath: /grafana-etc
{{- if .Values.postgres.backup.enabled }}
        - image: {{.Values.postgres.backup.repository}}:{{.Values.postgres.backup.image_version}}
          name: backup
          env:
            - name: MY_POD_NAME
              value: {{.Values.postgres.backup.name}}
            - name: MY_POD_NAMESPACE
              value: {{.Release.Namespace}}
            - name: OS_AUTH_URL
              value: {{.Values.postgres.backup.os_auth_url}}
            - name: OS_AUTH_VERSION
              value: "3"
            - name: OS_USERNAME
              value: {{.Values.postgres.backup.os_username}}
            - name: OS_USER_DOMAIN_NAME
              value: {{.Values.postgres.backup.os_user_domain}}
            - name: OS_PROJECT_NAME
              value: {{.Values.postgres.backup.os_project_name}}
            - name: OS_PROJECT_DOMAIN_NAME
              value: {{.Values.postgres.backup.os_project_domain}}
            - name: OS_REGION_NAME
              value: {{.Values.postgres.backup.os_region_name}}
            - name: OS_PASSWORD
              value: {{.Values.postgres.backup.os_password | quote}}
            - name: BACKUP_PGSQL_FULL
              value: {{.Values.postgres.backup.interval_full | quote}}
{{- end }}
