# Default values for backup-replication.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
repository: sapcc/backup-etcd
image_version: v0.0.17

# Enable metric data
metrics_enabled: false
metrics_port: 9189

# this value are seconds 864000 are 10 days
backup_expire_after: 864000
# this value are seconds 1800 are 30 minutes = 30 minutes * 60 seconds
backup_interval: 1800

# backup storage settings for swift
backup_os_auth_url: DEFINED-IN-REGION-SECRETS
backup_os_username: db_backup
backup_os_user_domain: Default
backup_os_project_name: master
backup_os_project_domain: ccadmin
backup_os_region_name: DEFINED-IN-REGION-SECRETS
backup_os_password: DEFINED-IN-REGION-SECRETS
